spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_PACYORKY_USER}
    password: ${PG_PACYORKY_PASS}
    url: ${DB_PACYORKY_HOST}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

